#!/bin/sh

xmldoc \
	--source panes.xml \
	--output output/ \
	--php static/panes/ \
	--image images/panes/ \
	--download files/panes/ \
	--cms protected/docs/panes.csv \
	--linkprefix panes/ \
	--imageprefix ../../images/panes/ \
	--downloadprefix ../../files/panes/