#!/bin/sh

# Copyright 2021, Stephen Fryatt (info@stevefryatt.org.uk)
#
# This file is part of Pane Tutorial:
#
#   http://www.stevefryatt.org.uk/software/
#
# Licensed under the EUPL, Version 1.2 only (the "Licence");
# You may not use this work except in compliance with the
# Licence.
#
# You may obtain a copy of the Licence at:
#
#   http://joinup.ec.europa.eu/software/page/eupl
#
# Unless required by applicable law or agreed to in
# writing, software distributed under the Licence is
# distributed on an "AS IS" basis, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the Licence for the specific language governing
# permissions and limitations under the Licence.

xmldoc \
	--source panes.xml \
	--output output/ \
	--php static/panes/ \
	--image images/panes/ \
	--download files/panes/ \
	--cms protected/docs/panes.csv \
	--linkprefix panes/ \
	--imageprefix ../../images/panes/ \
	--downloadprefix ../../files/panes/